mysql:
  address: "10.203.96.205:3306"
  database: "my_database"
  username: "rwuser"
  password: "nmlab301"
smtp:
  host: "smtp.zju.edu.cn"
  port: 25
  account: "22060112@zju.edu.cn"
  password: "201609xyz"